user:
  name: dev-config-server
spring:
  application:
    name: application-dev-server

server:
  port: 9095
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true
