server:
  port: 9095

user:
  name: dev-config-server
spring:
  application:
    name: application-dev-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
